### ISSUE TITLE
RangeError: WebAssembly.Instance(): Out of memory: wasm memory

### ISSUE THREAD

**Issue by CrazyFlasher** [pixijs/assetpack#52]
Trying to build assets from any of the game:
https://github.com/pixijs/open-games

For ex:
https://github.com/pixijs/open-games/tree/main/bubbo-bubbo
`npm run build-assets`

Error:
```
RangeError: WebAssembly.Instance(): Out of memory: wasm memory
    at instantiateSync (C:\work\projects\open-games\puzzling-potions\node_modules\ttf2woff2\jssrc\ttf2woff2.js:1:8181)
    at createWasm (C:\work\projects\open-games\puzzling-potions\node_modules\ttf2woff2\jssrc\ttf2woff2.js:1:9223)
    at Object.<anonymous> (C:\work\projects\open-games\puzzling-potions\node_modules\ttf2woff2\jssrc\ttf2woff2.js:1:34304)
```

Node.js v16.14.0.
Windows 11

**Comment by Zyie** [comment]
we have just released 1.0 and i've not been able to reproduce this issue on the latest version, so going to close this out for now

if this is still an issue for you let me know and i can take another look
